# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160620_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='x',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='blob',
            name='y',
            field=models.IntegerField(default=None),
        ),
    ]
