# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_world_world_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='world',
            name='blob',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Blob'),
        ),
    ]
