# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160617_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='world_coords',
        ),
    ]
