# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_world_world_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='world_coords',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
