# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=None)),
                ('y', models.IntegerField(default=None)),
                ('stage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_coords', models.TextField(default='', max_length=10000)),
                ('name', models.TextField(default='', max_length=200)),
                ('x_lower_bound', models.IntegerField(default=0)),
                ('x_upper_bound', models.IntegerField(default=50)),
                ('y_lower_bound', models.IntegerField(default=0)),
                ('y_upper_bound', models.IntegerField(default=50)),
                ('day', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorldRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.World')),
            ],
        ),
        migrations.AddField(
            model_name='blob',
            name='world',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.World'),
        ),
    ]
