# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldregister',
            name='world',
        ),
        migrations.AddField(
            model_name='world',
            name='world_register',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.WorldRegister'),
        ),
    ]
