# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='x_lower_bound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='x_upper_bound',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='world',
            name='y_lower_bound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='world',
            name='y_upper_bound',
            field=models.IntegerField(default=50),
        ),
    ]
