# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160620_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='status_message',
            field=models.TextField(default='', max_length=100),
        ),
    ]
