# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blob_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='stage',
            field=models.IntegerField(default=0),
        ),
    ]
