# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160621_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='status_message',
        ),
    ]
